version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.host=0.0.0.0
    ports:
      - 9200:9200

  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7687:7687

  api:
    build: .
    depends_on:
      - elasticsearch
      - neo4j
    ports:
      - 8000:8000
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - NEO4J_URI=bolt://neo4j:7687